# 放开actuator的所有监控url
management:
  endpoints:
    web:
      exposure:
        include: "*"

foo:
  datasource:
    url: jdbc:h2:mem:foo
    username: sa
    password:

bar:
  datasource:
    url: jdbc:h2:mem:bar
    username: sa
    password:

# 咖啡馆项目相关配置
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

mybatis:
  type-handlers-package: com.gpy.springalltong.mybatisdemo.handler
  configuration:
    map-underscore-to-camel-case: true