# 放开actuator的所有监控url
management:
  endpoints:
    web:
      exposure:
        include: "*"
foo:
  datasource:
    url: jdbc:h2:mem:foo
    username: sa
    password:

bar:
  datasource:
    url: jdbc:h2:mem:bar
    username: sa
    password:

# 咖啡馆项目相关配置
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    mongodb:
      uri: mongodb://root:123456@123.249.17.213:27017/springtong

#      password: admin
#      username: admin
#      authentication-database: admin
#      host: 123.249.17.213
#      port: 27017
#      database: springtong

mybatis:
  type-handlers-package: com.gpy.springalltong.mybatisdemo.handler
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8989

redis:
  host: 123.249.17.213
  maxTotal: 5
  maxIdle: 5
  testOnBorrow: true

#  db.createUser(
#      {
#          user: "root",
#          pwd: "123456",
#          roles: [
#                {role: "readWrite", db: "springtong"}
#            ]
#      }
# );
